[package]
name = "backend"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[dependencies]
futures = "^0.1.20"
rocket = "^0.4.0-rc.1"
serde_json = "^1.0.33"

rocket_cors = "^0.4.0"

shared = { path = "shared" }