[package]
name = "todomvc"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
wasm-bindgen = "^0.2.37"
web-sys = "^0.3.6"

serde = { version = "^1.0.80", features = ['derive'] }
