language: rust
rust:
  - nightly
os:
  - linux
  - osx
# Travis doesn't seem to handle Windows tests correctly. Triggers failures with
# no reason listed, despite passing on local machine.
#  - windows
addons:
  firefox: latest
cache: cargo
before_script:
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-bindgen-cli --vers 0.2.33 || true
  - cargo install wasm-pack --vers 0.6.0 || true
script:
  - cargo build --tests --target wasm32-unknown-unknown
  - wasm-pack test --headless --firefox
