[package]
name = "rebar"
version = "0.1.0"
description = "A frontend browser framework for Rust, via WebAssembly"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
license = "MIT"
repository = "https://www.github.com/David-OConnor/framework"
documentation = "https://docs.rs/framework"
readme = "./README.md"
keywords = ["wasm", "frontend", "framework", "web"]
categories = ["wasm", "web-programming", ""]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = {version = "^0.2.28", features = ["nightly"]}
proc_macros = { path = "proc_macros"}
js-sys = "^0.3.5"

# todo temp
futures = "0.1.25"
int_hash = "0.1.1"
wasm-bindgen-futures = "0.3"

[dependencies.web-sys]
version = "^0.3.4"
features = [
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "History",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "Location",
    "MouseEvent",
    "Node",
    "NodeList",
    "Performance",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Storage",
    "Text",
    "console",
"Window",
]


[workspace]
members = [
#    "proc_macros",
    #"examples/rosetta_stone/self",
]


# wasm-bindgen target/wasm32-unknown-unknown/debug/rebar.wasm --no-modules --out-dir ./pkg