[package]
name = "seed"
version = "0.2.1"
description = "A Rust framework for creating web apps, using WebAssembly"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
license = "MIT"
repository = "https://www.github.com/David-OConnor/seed"
homepage = "https://seed-rs.org"
documentation = "https://docs.rs/seed"
readme = "README.md"
keywords = ["wasm", "webassembly", "frontend", "framework", "web"]
categories = ["wasm", "web-programming"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
#proc-macro = true

[dev-dependencies]
wasm-bindgen-test = "^0.2.29" # NOTE: keep in sync with wasm-bindgen version

[dependencies]
wasm-bindgen = {version = "^0.2.29", features = ["serde-serialize"]}
js-sys = "0.3.6"
console_error_panic_hook = "^0.1.5"
serde = { version = "^1.0.80", features = ['derive'] }
serde_json = "^1.0.33"
futures = "^0.1.20"
wasm-bindgen-futures = "^0.3.6"

# Markdown conversion
pulldown-cmark = "^0.2.0"

[dependencies.web-sys]
version = "0.3.4"
features = [
    "AbortController",
    "AbortSignal",
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "Headers",
    "History",
    "HtmlElement",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "HtmlButtonElement",
    "Location",
    "MouseEvent",
    "Node",
    "NodeList",
    "Performance",
    "PopStateEvent",
    "ReferrerPolicy",
    "Request",
    "RequestCache",
    "RequestCredentials",
    "RequestInit",
    "RequestMode",
    "RequestRedirect",
    "Response",
    "Storage",
    "Text",
    "console",
    "Window",
    "KeyboardEvent",
    "InputEvent",
]

[workspace]
members = [
    "examples/counter",
    "examples/server_interaction",
    "examples/todomvc",
    "examples/window_events",
]

exclude = [
    # We experience compile-target incompatibility if including in a workspace.
    "examples/server_integration"
]
