[package]
name = "seed"
version = "0.1.0"
description = "A frontend framework for Rust, via WebAssembly"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
license = "MIT"
repository = "https://www.github.com/David-OConnor/seed"
homepage = "https://www.github.com/David-OConnor/seed"
documentation = "https://docs.rs/seed"
readme = "README.md"
keywords = ["wasm", "frontend", "framework", "web", "bindgen"]
categories = ["wasm", "web-programming"]
edition = "2018"

[dependencies]
wasm-bindgen = {version = "0.2.28", features = ["nightly", "serde-serialize"]}
js-sys = "0.3.5"

serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"

# temp?
futures = "0.1.20"
wasm-bindgen-futures = "0.3.6"

[dependencies.web-sys]
version = "0.3.4"
features = [
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "Headers",
    "History",
    "HtmlElement",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "Location",
    "MouseEvent",
    "Node",
    "NodeList",
    "Performance",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Storage",
    "Text",
    "console",
    "Window",
    "KeyboardEvent",
    "InputEvent",
]


[workspace]
members = [
    "examples/counter",
    "examples/todomvc",
    "examples/server_interaction",
]
