[package]
name = "rosetta"
version = "0.1.0"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2.28"
framework = { path = "../../../"}
