[package]
name = "frontend"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.2.1"
wasm-bindgen = "^0.2.29"
web-sys = "^0.3.6"
shared = { path = "../shared"}
