[package]
name = "frontend"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures = "^0.1.20"
seed = { path = "../../../"}
wasm-bindgen = "^0.2.37"
web-sys = "^0.3.6"
shared = { path = "../shared"}
