[package]
name = "proc_macros"
version = "0.1.0"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
#framework = { path = "../"}
syn = "^0.15.21"
quote = "^0.6.10"