[package]
name = "websocket"
version = "0.1.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
futures = "*"
js-sys = "*"
seed = { path = "../../" }
serde = "1"
serde_derive = "1"
serde_json = "1"
wasm-bindgen = "*"

pretty_env_logger = { version = "*", optional = true }
warp = { version = "*", optional = true }

[dependencies.web-sys]
version = "*"
features = ["WebSocket", "MessageEvent", "BinaryType"]

[features]
default = ["server"]
server = ["warp", "pretty_env_logger"]
